Rework the build system
It mainly rewrites the main Makefile and the configure script. Also,
kill the HPC emergency and liburing for now, we will get them working
in the next merges.

BTW, the diffstat is nice:

  207 files changed, 388 insertions(+), 37148 deletions(-)

I love deleted code.

Signed-off-by: Ammar Faizi <ammarfaizi2@gnuweeb.org>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,354 +1,363 @@
 #!/bin/sh
 #
-# Thanks to liburing (https://github.com/axboe/liburing)
+# SPDX-License-Identifier: GPL-2.0-only
+#
+# Copyright (C) 2023  Ammar Faizi <ammarfaizi2@gnuweeb.org>
+#
+# Inspired by liburing's configure script.
 #
 
-cc=${CC:-gcc}
-cxx=${CXX:-g++}
-ld=${LD:-$cc}
+set -e;
 
-CONFIG_LINUX=y
+cc=${CC:-gcc};
+cxx=${CXX:-g++};
+ld=${LD:-$cc};
+build_dir=${O:-$(dirname $(realpath $0))};
 
-USER_CFLAGS=${CFLAGS}
-USER_CXXFLAGS=${CXXFLAGS}
-USER_LDFLAGS=${LDFLAGS}
-USER_LIB_LDFLAGS=${LIB_LDFLAGS}
-
-
-if test -z "$CONFIG_IO_URING"; then
-  CONFIG_IO_URING=y
-fi
+USER_CFLAGS="${CFLAGS}";
+USER_CXXFLAGS="${CXXFLAGS}";
+USER_LDFLAGS="${LDFLAGS}";
+USER_LIB_LDFLAGS="${LIB_LDFLAGS}";
 
 for opt do
-  optarg=$(expr "x$opt" : 'x[^=]*=\(.*\)')
-  case "$opt" in
-  --help|-h) show_help=yes
-  ;;
-  --prefix=*) prefix="$optarg"
-  ;;
-  --includedir=*) includedir="$optarg"
-  ;;
-  --libdir=*) libdir="$optarg"
-  ;;
-  --libdevdir=*) libdevdir="$optarg"
-  ;;
-  --mandir=*) mandir="$optarg"
-  ;;
-  --datadir=*) datadir="$optarg"
-  ;;
-  --cc=*) cc="$optarg"
-  ;;
-  --cxx=*) cxx="$optarg"
-  ;;
-  --ld=*) ld="$optarg"
-  ;;
-  --cflags=*) USER_CFLAGS="$optarg"
-  ;;
-  --cxxflags=*) USER_CXXFLAGS="$optarg"
-  ;;
-  --ldflags=*) USER_LDFLAGS="$optarg"
-  ;;
-  --lib-ldflags=*) USER_LIB_LDFLAGS="$optarg"
-  ;;
-  --32-bit) USE_32_BIT=y
-  ;;
-  --gui) CONFIG_GUI=y
-  ;;
-  *)
-    echo "ERROR: unknown option $opt"
-    echo "Try '$0 --help' for more information"
-    exit 1
-  ;;
-  esac
+	optarg=$(expr "x$opt" : 'x[^=]*=\(.*\)' || true);
+	case "$opt" in
+	--help|-h)
+		show_help=yes;
+	;;
+	--build-dir=*)
+		build_dir="$optarg";
+	;;
+	--prefix=*)
+		prefix="$optarg";
+	;;
+	--includedir=*)
+		includedir="$optarg";
+	;;
+	--libdir=*)
+		libdir="$optarg";
+	;;
+	--libdevdir=*)
+		libdevdir="$optarg";
+	;;
+	--mandir=*)
+		mandir="$optarg";
+	;;
+	--datadir=*)
+		datadir="$optarg";
+	;;
+	--cc=??*)
+		cc="$optarg";
+	;;
+	--cxx=*)
+		cxx="$optarg";
+	;;
+	--gui)
+		use_gui="yes";
+	;;
+	*)
+		echo "ERROR: unknown option $opt";
+		echo "Try '$0 --help' for more information";
+		exit 1;
+	;;
+	esac;
 done
 
-if test "$USE_32_BIT" = "y"; then
-  USER_CFLAGS="-m32 ${USER_CFLAGS}";
-  USER_CXXFLAGS="-m32 ${USER_CXXFLAGS}";
-  USER_LDFLAGS="-m32 ${USER_LDFLAGS}";
-fi
-
 if test -z "$prefix"; then
-  prefix=/usr
-fi
-if test -z "$includedir"; then
-  includedir="$prefix/include"
-fi
-if test -z "$libdir"; then
-  libdir="$prefix/lib"
-fi
-if test -z "$libdevdir"; then
-  libdevdir="$prefix/lib"
-fi
-if test -z "$mandir"; then
-  mandir="$prefix/man"
-fi
-if test -z "$datadir"; then
-  datadir="$prefix/share"
+	prefix=/usr;
 fi
 
-if test x"$libdir" = x"$libdevdir"; then
-  relativelibdir=""
-else
-  relativelibdir="$libdir/"
+if test -z "$includedir"; then
+	includedir="$prefix/include";
+fi
+
+if test -z "$libdir"; then
+	libdir="$prefix/lib";
+fi
+
+if test -z "$libdevdir"; then
+	libdevdir="$prefix/lib";
+fi
+
+if test -z "$mandir"; then
+	mandir="$prefix/man";
+fi
+
+if test -z "$datadir"; then
+	datadir="$prefix/share";
 fi
 
 if test "$show_help" = "yes"; then
 cat <<EOF
 
-Usage: configure [options]
+Usage: ./configure [options]
+
 Options: [defaults in brackets after descriptions]
-  --help                   print this message
-  --prefix=PATH            install in PATH [$prefix]
-  --includedir=PATH        install headers in PATH [$includedir]
-  --libdir=PATH            install runtime libraries in PATH [$libdir]
-  --libdevdir=PATH         install development libraries in PATH [$libdevdir]
-  --mandir=PATH            install man pages in PATH [$mandir]
-  --datadir=PATH           install shared data in PATH [$datadir]
-  --cc=CMD                 use CMD as the C compiler
-  --cxx=CMD                use CMD as the C++ compiler
-  --ld=CMD                 use CMD as the linker
-  --cflags=FLAGS           set C compiler flags
-  --cxxflags=FLAGS         set C++ compiler flags
-  --ldflags=FLAGS          set linker flags
-  --lib-ldflags=FLAGS      set library linker flags (end of the command)
-  --32-bit                 set 32-bit build flags
-  --gui                    compile with GUI support (GTK-3)
+  --help                   Print this message
+  --build-dir=PATH         Set build output in PATH [$build_dir]
+  --prefix=PATH            Install in PATH [$prefix]
+  --includedir=PATH        Install headers in PATH [$includedir]
+  --libdir=PATH            Install runtime libraries in PATH [$libdir]
+  --libdevdir=PATH         Install development libraries in PATH [$libdevdir]
+  --mandir=PATH            Install man pages in PATH [$mandir]
+  --datadir=PATH           Install shared data in PATH [$datadir]
+  --cc=CMD                 Use CMD as the C compiler
+  --cxx=CMD                Use CMD as the C++ compiler
+  --gui                    Add the GUI support
 EOF
-exit 0
+exit 0;
 fi
 
-TMP_DIRECTORY="$(mktemp -d)"
-TMPC="$TMP_DIRECTORY/tmpfile.c"
-TMPC2="$TMP_DIRECTORY/tmpfile-2.c"
-TMPO="$TMP_DIRECTORY/tmpfile.o"
-TMPE="$TMP_DIRECTORY/tmpfile.exe"
+mkdir -pv "${build_dir}";
+build_dir="$(realpath "${build_dir}")";
 
-touch $TMPC $TMPC2 $TMPO $TMPE
+tmp_dir="${build_dir}/.tmp";
+tmp_o="${tmp_dir}/tmp.o";
+tmp_c="${tmp_dir}/tmp.c";
+tmp_cpp="${tmp_dir}/tmp.cpp";
+tmp_exe="${tmp_dir}/tmp.exe";
+
+mkdir -pv "${tmp_dir}";
+rm -f "${build_dir}/config.log";
+
+config_make="${build_dir}/config.make";
+config_h="${build_dir}/config.h";
+config_log="${build_dir}/config.log";
+
 # NB: do not call "exit" in the trap handler; this is buggy with some shells;
 # see <1285349658-3122-1-git-send-email-loic.minier@linaro.org>
-trap "rm -rf $TMP_DIRECTORY" EXIT INT QUIT TERM
+trap "rm -rf \"${tmp_dir}\"" EXIT INT HUP QUIT TERM;
 
-config_host_mak="config-host.mak"
-config_host_h="config-host.h"
-
-rm -rf config.log
-rm -rf $config_host_mak
-rm -rf $config_host_h
-
-fatal() {
-  echo $@
-  echo "Configure failed, check config.log and/or the above output"
-  rm -rf $config_host_mak
-  rm -rf $config_host_h
-  exit 1
+fatal()
+{
+	echo $@;
+	echo "Configure failed, check config.log and/or the above output";
+	rm -f "${config_make}";
+	rm -f "${config_h}";
+	exit 1;
 }
 
 # Print result for each configuration test
-print_config() {
-  printf "%-30s%s\n" "$1" "$2"
+print_config()
+{
+	printf "  %-55s%s\n" "$1" "$2";
 }
 
-# Default CFLAGS
-CFLAGS="${USER_CFLAGS}";
-CXXFLAGS="${USER_CFLAGS}";
-LDFLAGS="${USER_LDFLAGS}";
-LIB_LDFLAGS="${USER_LIB_LDFLAGS}";
+# Default flags.
+CFLAGS="-O2 -D_GNU_SOURCE -include ${build_dir}/config.h";
+CXXFLAGS="-O2 -D_GNU_SOURCE -include ${build_dir}/config.h";
+LDFLAGS="-O2";
+LIB_LDFLAGS="-lpthread";
 
-# Print configure header at the top of $config_host_h
-echo "/*" > $config_host_h
-echo " * Automatically generated by configure - do not modify" >> $config_host_h
-printf " * Configured with:" >> $config_host_h
-printf " * '%s'" "$0" "$@" >> $config_host_h
-echo "" >> $config_host_h
-echo " */" >> $config_host_h
+# Print configure header at the top of $config_h.
+printf "/*\n" > $config_h;
+printf " * Automatically generated by configure - do not modify!\n" >> $config_h;
+printf " *\n" >> $config_h;
+printf " * Configured with:" >> $config_h;
+printf " * '%s'" "$0" "$@" >> $config_h;
+printf "\n" >> $config_h;
+printf " */\n" >> $config_h;
 
-echo "# Automatically generated by configure - do not modify" > $config_host_mak
-printf "# Configured with:" >> $config_host_mak
-printf " '%s'" "$0" "$@" >> $config_host_mak
-echo >> $config_host_mak
+printf "# Automatically generated by configure - do not modify!\n" > $config_make;
+printf "# Configured with:" >> $config_make;
+printf " '%s'" "$0" "$@" >> $config_make;
+printf "\n" >> $config_make;
 
-do_cxx() {
-  # Run the compiler, capturing its output to the log.
-  echo $cxx "$@" >> config.log
-  $cxx "$@" >> config.log 2>&1 || return $?
-  return 0
+add_config_make()
+{
+	printf "%s\n" "$1=$2" >> $config_make;
 }
 
-do_cc() {
-  # Run the compiler, capturing its output to the log.
-  echo $cc "$@" >> config.log
-  $cc "$@" >> config.log 2>&1 || return $?
-  # Test passed. If this is an --enable-werror build, rerun
-  # the test with -Werror and bail out if it fails. This
-  # makes warning-generating-errors in configure test code
-  # obvious to developers.
-  if test "$werror" != "yes"; then
-    return 0
-  fi
-  # Don't bother rerunning the compile if we were already using -Werror
-  case "$*" in
-    *-Werror*)
-       return 0
-    ;;
-  esac
-  echo $cc -Werror "$@" >> config.log
-  $cc -Werror "$@" >> config.log 2>&1 && return $?
-  echo "ERROR: configure test passed without -Werror but failed with -Werror."
-  echo "This is probably a bug in the configure script. The failing command"
-  echo "will be at the bottom of config.log."
-  fatal "You can run configure with --disable-werror to bypass this check."
+add_config_h()
+{
+	printf "%s\n" "#define $1" >> $config_h;
 }
 
-compile_prog() {
-  local_cflags="$1";
-  local_ldflags="$2 $LIBS";
-  echo "Compiling test case $3" >> config.log;
-  do_cc -D_GNU_SOURCE $CFLAGS $local_cflags -o $TMPE $TMPC $LDFLAGS $local_ldflags;
+add_config()
+{
+	add_config_make $1 "y";
+	add_config_h $1;
+	print_config "Adding $1=y";
 }
 
-compile_prog_cxx() {
-  local_cflags="$1";
-  local_ldflags="$2 $LIBS";
-  echo "Compiling test case $3" >> config.log;
-  do_cxx -D_GNU_SOURCE $CXXFLAGS $local_cflags -o $TMPE $TMPC $LDFLAGS $local_ldflags;
+add_make_var()
+{
+	printf "%s\n" "$1=$2" >> $config_make;
 }
 
-has() {
-  type "$1" >/dev/null 2>&1
+do_cc()
+{
+	# Run the compiler, capturing its output to the log.
+	echo "${cc}" "$@" >> $config_log;
+	"${cc}" "$@" >> $config_log 2>&1 || return $?;
+	return 0;
 }
 
-output_mak() {
-  echo "$1=$2" >> $config_host_mak
+do_cxx()
+{
+	# Run the compiler, capturing its output to the log.
+	echo "${cxx}" "$@" >> $config_log;
+	"${cxx}" "$@" >> $config_log 2>&1 || return $?;
+	return 0;
 }
 
-output_sym() {
-  output_mak "$1" "y"
-  echo "#define $1" >> $config_host_h
+compile_cc()
+{
+	local_cflags="$1";
+	local_ldflags="$2 $LIBS";
+	printf "\n\nCompiling test case %s:\n" "$3" >> $config_log;
+	do_cc $CFLAGS $local_cflags -o "${tmp_exe}" "${tmp_c}" \
+		${LDFLAGS} ${local_ldflags};
 }
 
-print_and_output_mak() {
-  print_config "$1" "$2"
-  output_mak "$1" "$2"
+compile_cxx()
+{
+	local_cxxflags="$1";
+	local_ldflags="$2 $LIBS";
+	printf "\n\nCompiling test case %s:" "$3" >> $config_log;
+	do_cxx $CXXFLAGS $local_cxxflags -o "${tmp_exe}" "${tmp_cpp}" \
+		${LDFLAGS} ${local_ldflags};
 }
-print_and_output_mak "prefix" "$prefix"
-print_and_output_mak "includedir" "$includedir"
-print_and_output_mak "libdir" "$libdir"
-print_and_output_mak "libdevdir" "$libdevdir"
-print_and_output_mak "relativelibdir" "$relativelibdir"
-print_and_output_mak "mandir" "$mandir"
-print_and_output_mak "datadir" "$datadir"
 
-
-########################################################################
-# Check HPC Emergency Support
-#
-# Currently it's only supported for Linux x86-64.
-#
-if test -z "$CONFIG_HPC_EMERGENCY"; then
-
-  CONFIG_HPC_EMERGENCY="no"
-  cat > $TMPC << EOF
-#if !defined(__x86_64__) || !defined(__linux__)
-#error "HPC emergency is not supported."
-#endif
+__has_cflags()
+{
+	cat > $tmp_c << EOF
 int main(void)
 {
-  return 0;
+	return 0;
 }
 EOF
+	compile_cc "-Werror $1" "" "$1" || return $?;
+	return 0;
+}
 
-  if compile_prog "" "" "CONFIG_HPC_EMERGENCY"; then
-    CONFIG_HPC_EMERGENCY="y"
-  fi
-fi # if test -z "$CONFIG_HPC_EMERGENCY";
-########################################################################
+__has_cxxflags()
+{
+	cat > $tmp_cpp << EOF
+int main(void)
+{
+	return 0;
+}
+EOF
+	compile_cxx "-Werror $1" "" "$1" || return $?;
+	return 0;
+}
 
+__has_c_and_cxxflags()
+{
+	__has_cflags $1 || return $?;
+	__has_cxxflags $1 || return $?;
+	return 0;
+}
 
+add_c_flag()
+{
+	local_append_flag=$1;
+	if test ! -z "$2"; then
+		local_append_flag="$2";
+	fi;
 
-########################################################################
-#
-# Get the compiler type. We only support GCC and Clang!
-#
-if printf "" | "$cc" -dM -E - | grep __clang__ >> config.log; then
-  CC_TYPE=__clang
-else
-  if printf "" | "$cc" -dM -E - | grep __GNUC__ >> config.log; then
-    CC_TYPE=__gcc
-  else
-    echo "CC is not supported, current CC is \"$cc\"";
-    exit 1;
-  fi
-fi
-print_config "CC_TYPE" "$CC_TYPE";
-echo "CC_TYPE := $CC_TYPE" >> $config_host_mak;
+	if __has_cflags $1; then
+		ret=0;
+		support="yes";
+		CFLAGS="$1 ${CFLAGS}";
+	else
+		ret=1;
+		support="no";
+	fi;
 
+	print_config "Does CC  support ${1}?" "${support}";
+	return $ret;
+}
 
-if printf "" | "$cxx" -dM -E - | grep __clang__ >> config.log; then
-  CXX_TYPE=__clang
-else
-  if printf "" | "$cxx" -dM -E - | grep __GNUC__ >> config.log; then
-    CXX_TYPE=__gcc
-  else
-    echo "CXX is not supported, current CXX is \"$cxx\"";
-    exit 1;
-  fi
-fi
-print_config "CXX_TYPE" "$CXX_TYPE";
-echo "CXX_TYPE := $CXX_TYPE" >> $config_host_mak;
-########################################################################
+add_cxx_flag()
+{
+	local_append_flag=$1;
+	if test ! -z "$2"; then
+		local_append_flag="$2";
+	fi;
 
+	if __has_cxxflags $1; then
+		support="yes";
+		CXXFLAGS="$1 ${CXXFLAGS}";
+	else
+		support="no";
+	fi;
+	ret=$?;
 
-########################################################################
-#
-# Get current git commit sha1.
-#
-GIT_HASH=$(git log --pretty="%H" -1)
-if test ! -z "$GIT_HASH"; then
-  echo "GIT_HASH := $GIT_HASH" >> $config_host_mak;
-  echo "EXTRAVERSION := \$(EXTRAVERSION)-\$(GIT_HASH)" >> $config_host_mak;
-  print_config "GIT_HASH" "$GIT_HASH";
-else
-  print_config "GIT_HASH" "cannot get commit sha1";
-fi
-########################################################################
+	print_config "Does CXX support ${1}?" "${support}";
+	return $ret;
+}
 
-if test "$CONFIG_GUI" = "y"; then
-  output_sym "CONFIG_GUI";
+add_c_and_cxx_flag()
+{
+	add_c_flag "$@";
+	add_cxx_flag "$@";
+}
+
+printf "\n%s:\n" "Compilers";
+print_config "CC" "${cc}";
+print_config "CXX" "${cxx}";
+
+# Don't exit if add_* functions return non-zero.
+set +e;
+
+printf "\n%s:\n" "-W flags";
+add_c_and_cxx_flag "-Wall";
+add_c_and_cxx_flag "-Wextra";
+add_c_and_cxx_flag "-Wsequence-point";
+add_c_and_cxx_flag "-Wunreachable-code";
+add_c_and_cxx_flag "-Wunreachable-code-loop-increment";
+add_c_and_cxx_flag "-Wformat-signedness";
+add_c_and_cxx_flag "-Wformat-security";
+add_c_and_cxx_flag "-Wformat";
+add_c_and_cxx_flag "-Wstack-usage=4096";
+add_c_and_cxx_flag "-Wmissing-prototypes";
+add_c_and_cxx_flag "-Wstrict-prototypes";
+add_c_and_cxx_flag "-Wmissing-variable-declarations";
+add_c_and_cxx_flag "-Wstrict-aliasing=3";
+add_c_and_cxx_flag "-Wshorten-64-to-32";
+add_c_and_cxx_flag "-Wunsafe-loop-optimizations";
+
+printf "\n%s:\n" "-f flags";
+add_c_and_cxx_flag "-fno-stack-protector";
+add_c_and_cxx_flag "-fdata-sections";
+add_c_and_cxx_flag "-ffunction-sections";
+add_c_and_cxx_flag "-fno-strict-aliasing";
+add_c_and_cxx_flag "-fvisibility=hidden";
+add_c_and_cxx_flag "-flto" && LDFLAGS="-flto ${LDFLAGS}";
+add_c_and_cxx_flag "-fpie -fPIE" && LDFLAGS="-fpie -fPIE ${LDFLAGS}";
+
+printf "\n%s:\n" "Misc flags";
+LDFLAGS="-rdynamic ${LDFLAGS}";
+add_c_and_cxx_flag "-ggdb3" && LDFLAGS="-ggdb3 ${LDFLAGS}";
+
+# Bring it back!
+set -e;
+
+printf "\n%s:\n" "CONFIG";
+add_config "CONFIG_POLL";
+add_config "CONFIG_EPOLL";
+add_config "CONFIG_IO_URING";
+add_config "CONFIG_TEAVPN_SERVER";
+add_config "CONFIG_TEAVPN_CLIENT";
+add_config "CONFIG_LINUX";
+
+if test "${use_gui}" = "yes"; then
+	add_config "CONFIG_GUI";
+	gtk3_cflags=`pkg-config --cflags gtk+-3.0`;
+	gtk3_lib_ldflags=`pkg-config --libs gtk+-3.0`;
+	CFLAGS="${CFLAGS} ${gtk3_cflags}";
+	CXXFLAGS="${CXXFLAGS} ${gtk3_cflags}";
+	LIB_LDFLAGS="${LD_FLAGS} ${gtk3_lib_ldflags}";
 fi;
-print_config "CONFIG_GUI" "$CONFIG_GUI";
 
-if test "$CONFIG_LINUX" = "y"; then
-  output_sym "CONFIG_LINUX";
-fi;
-print_config "CONFIG_LINUX" "$CONFIG_LINUX";
-
-if test "$CONFIG_IO_URING" = "y"; then
-  output_sym "CONFIG_IO_URING";
-fi;
-print_config "CONFIG_IO_URING" "$CONFIG_IO_URING";
-
-if test "$CONFIG_HPC_EMERGENCY" = "y"; then
-  output_sym "CONFIG_HPC_EMERGENCY";
-fi;
-print_config "CONFIG_HPC_EMERGENCY" "$CONFIG_HPC_EMERGENCY";
-
-echo "CC := $cc" >> $config_host_mak;
-print_config "CC" "$cc";
-echo "CXX := $cxx" >> $config_host_mak;
-print_config "CXX" "$cxx";
-echo "LD := $ld" >> $config_host_mak;
-print_config "LD" "$ld";
-
-echo "CFLAGS := $CFLAGS" >> $config_host_mak;
-print_config "USER_CFLAGS" "$USER_CFLAGS";
-
-echo "CXXFLAGS := $CXXFLAGS" >> $config_host_mak;
-print_config "USER_CXXFLAGS" "$USER_CXXFLAGS";
-
-echo "LDFLAGS := $LDFLAGS" >> $config_host_mak;
-print_config "USER_LDFLAGS" "$USER_LDFLAGS";
-
-echo "LIB_LDFLAGS := $LIB_LDFLAGS" >> $config_host_mak;
-print_config "USER_LIB_LDFLAGS" "$USER_LIB_LDFLAGS";
-echo "---------------------------------------------------------------";
+add_make_var "CC" "${cc}";
+add_make_var "CXX" "${cxx}";
+add_make_var "CFLAGS" "$(echo "${CFLAGS} ${USER_CFLAGS}" | awk '{$1=$1};1')";
+add_make_var "CXXFLAGS" "$(echo "${CXXFLAGS} ${USER_CXXFLAGS}" | awk '{$1=$1};1')";
+add_make_var "LDFLAGS" "$(echo "${LDFLAGS} ${USER_LIB_LDFLAGS}" | awk '{$1=$1};1')";
+add_make_var "LIB_LDFLAGS" "$(echo "${LIB_LDFLAGS} ${USER_LIB_LDFLAGS}" | awk '{$1=$1};1')";
+printf "override O=%s\n" "${build_dir}" >> $config_make;
+ln -s "${config_make}" >> /dev/null 2>&1 || true;
+printf "\n";
